name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  Creational_Pattern:

    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Builder Pattern
        run: node creational/builder.js
      - name: Abstract Factory Pattern
        run: node creational/abstract-factory.js
      - name: Factory Pattern
        run: node creational/factory.js
      - name: Prototype Pattern
        run: node creational/prototype.js
      - name: Singleton Pattern
        run: node creational/singleton.js
